name: Build Windows with pyinstaller 

on:
  push:
    branches: master


    

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          
      - name: Run PyInstaller
        run: |
          python -m PyInstaller build.spec
          
      - uses: actions/upload-artifact@v2
        with:
          name: build_windows
          path: dist/pyDevInstaller.exe
